### ISSUE TITLE
eth-testrpc doesn't install cleanly from PyPI

### ISSUE THREAD

**Issue by maurycyp** [pipermerriam/eth-testrpc#12]
Installing eth-testrpc from PyPI is not clean.  Despite the fact that `jsonrpclib` and `ethereum` are listed as dependencies in `setup.py`, they need to be installed manually before running `pip install eth-testrpc`.

To reproduce this issue, make sure to use an empty virtual env.

**Comment by Georgi87** [comment]
The reason is a cyclic dependency:

The setup script imports the version from testrpc`from testrpc import __version__`. testrpc imports ethereum, which is not installed at that point. Thats why the setup fails if ethereum is not yet installed.

**Comment by pipermerriam** [comment]
This *should* be fixed.  The library has been significantly overhauled since this was opened.  Please re-open if this is still an issue.
