### ISSUE TITLE
testrpc.py", line 294, in eth_compileSolidity

### ISSUE THREAD

**Issue by mtgran** [pipermerriam/eth-testrpc#21]
Hi,

I get an error in testrpc.py performing the truffle deploy:

> $ truffle deploy --force
> Using environment development.
> Compiling BusinessPartnerFS.sol...
> 
> Server error:   File "/home/m9000/.local/lib/python2.7/site-packages/testrpc/testrpc.py", line 294, in eth_compileSolidity | KeyError: 'binary'

> Hint: Some clients don't send helpful error messages through the RPC. See client logs for more details.
> Warning: Compilation failed. See above. Used --force, continuing.

The eth-testrpc package ist up-to-date
https://gist.github.com/mtgran/d5c3f3cf7da1f4f6a09a

I am currently using Python 2.7.9 and solc 0.1.2-0/Release-Linux/g++/int

**Comment by ajunge** [comment]
I think this has todo with the change in solc command line arguments

**Comment by ethers** [comment]
@mtgran since you are using solc 0.1.2 you've probably updated pyethereum (you closed https://github.com/ethereum/pyethereum/issues/286)?  did that help?

**Comment by pipermerriam** [comment]
This *should* be fixed.  The library has been significantly overhauled since this was opened.  Please re-open if this is still an issue.
