### ISSUE TITLE
eth-testrpc installation errors (e.g. python)

### ISSUE THREAD

**Issue by skydogch** [pipermerriam/eth-testrpc#22]
Hi,

the installation of eth-testrpc raises several errors. Interessting is the python too:

http://pastebin.com/yKrXXMZa

The installation was done with "pip install eth-testrpc"
It seems that the installation uses a python3 library although python2.7 is needed.
If you see in the log, the library python2.7 is used in most part of the installation, but there is an error concerning the utils_py3.py library, between others

Regards
SkyDog

**Comment by pipermerriam** [comment]
This *should* be fixed.  The library has been significantly overhauled since this was opened.  Please re-open if this is still an issue.
