### ISSUE TITLE
eth_getTransactionReceipt logs

### ISSUE THREAD

**Issue by ethers** [pipermerriam/eth-testrpc#24]
as of testrpc 0.1.17 logs are missing from eth_getTransactionReceipt

**Comment by tcoulter** [comment]
Thanks @ethers. I don't believe this is still the case. If so, please reopen. Cheers!

**Comment by tcoulter** [comment]
Whoops, I'm on the wrong testrpc.

**Comment by pipermerriam** [comment]
This *should* be fixed.  The library has been significantly overhauled since this was opened.  Please re-open if this is still an issue.
