### ISSUE TITLE
truffle deploy throws error even when deploying an empty contract

### ISSUE THREAD

**Issue by tomlion** [pipermerriam/eth-testrpc#26]
I got "Error: The contract code couldn't be stored, please check your gas amount." when deploy an empty  contract against testrpc

**Comment by tcoulter** [comment]
Can you please include code that reproduces this error? Also include your TestRPC, Truffle and solc version numbers. Thanks!

**Comment by tomlion** [comment]
solc: 0.1.2-5c3bfd4b/.-/unknown/int
Truffle: v0.1.0
eth-testrpc:  0.1.17
ethereum: 1.0.1

The contract is an empty contract: `contract Test{}`

**Comment by pipermerriam** [comment]
This *should* be fixed.  The library has been significantly overhauled since this was opened.  Please re-open if this is still an issue.
