### ISSUE TITLE
Error: Method net_listening not supported.

### ISSUE THREAD

**Issue by hynese** [pipermerriam/eth-testrpc#33]
Greetings,

I'm running `testrpc` which seems to work fine.

I go to http://meteor-dapp-cosmo.meteor.com/ and I plug it in to localhost:8545 and I get this error:

```
Web3 Connected! HTTPProvider -> http://localhost:8545
Error: Method net_listening not supported.
```

**Comment by pipermerriam** [comment]
This is now supported.
