### ISSUE TITLE
After i execute the cmd "testrpc ", the console echos  "<generator object main at 0x7feae0364230>"

### ISSUE THREAD

**Issue by Aireed** [pipermerriam/eth-testrpc#48]
![image](https://cloud.githubusercontent.com/assets/8862395/17315833/93382a0a-58a1-11e6-9817-01b98e962ee6.png)

i can't find the process named testrpc ,and i can't find link which is listening 8545 port.

**Comment by pipermerriam** [comment]
@Aireed this should be fixed now in `0.7.0`.  Can you re-open if it isn't.
