### ISSUE TITLE
The `"earliest"` block identifier should return block #1

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/eth-testrpc#72]
### What was wrong?

Currently if you call `eth_getBlockByNumber("earliest")` you will get the genesis block which is block number 0.  Based on the behavior of `geth` and `parity`, this should be returning block number 1.
#### Cute Animal Picture

> put a cute animal picture here.

![t-ezkrmv](https://cloud.githubusercontent.com/assets/824194/19158493/2fd2e3a0-8ba6-11e6-87d6-c05943476d72.jpeg)

**Comment by DavidKnott** [comment]
@pipermerriam I'm on it!

**Comment by pipermerriam** [comment]
According to the docs for the JS API: https://github.com/ethereum/wiki/wiki/JavaScript-API#values-1

The genesis block is the appropriate return value for this.
