### ISSUE TITLE
Can't install eth-testrpc

### ISSUE THREAD

**Issue by manishlamichhane** [pipermerriam/eth-testrpc#74]
* `Python` Version: 2.7.6

* OS: linuxmint 17.03

### What was wrong?

![screenshot from 2016-10-16 13 25 24](https://cloud.githubusercontent.com/assets/4988114/19417109/3c9fe71c-93a4-11e6-9b0e-376f907e392b.png)

**Comment by pipermerriam** [comment]
Looks like you may be missing a system dependency lib-ffidev

**Comment by manishlamichhane** [comment]
libffi-dev and libffi6 both are in latest versions

**Comment by manishlamichhane** [comment]
I found out that autoconf and dh-autoreconf were not installed. Installing them both, did the trick.
